version: '3'

services:

  consul-agent-kv-put-me: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "kv put demo/user $USER"
    environment:
      CONSUL_HTTP_ADDR: "http://consul-server-bootstrap:8500"

  consul-agent-kv-get-all:
    <<: *consul-agent
    command: "kv get -recurse /demo"

  consul-template-me:
    image: hashicorp/consul-template:latest
    networks:
      - consul-demo
    command: "-consul-addr http://consul-server-bootstrap:8500 -template /tpl/in.tpl:/tpl/out.txt -once"
    volumes:
      - "./tpl:/tpl"
networks:
  consul-demo:
