version: '3'

services:

  consul-agent-kv-put-me: &consul-agent
    image: consul:latest
    networks:
      - consul-demo
    command: "kv put user $USER"
    environment:
      CONSUL_HTTP_ADDR: "http://consul-server-bootstrap:8500"

  consul-agent-kv-get-all:
    <<: *consul-agent
    command: "kv get -recurse /"

  consul-template-me:
    image: hashicorp/consul-template:latest
    networks:
      - consul-demo
    command: "-consul-addr http://consul-server-bootstrap:8500 -template /tpl/in.tpl:/tpl/out.txt -once"
    volumes:
      - "./tpl:/tpl"
#docker run --rm -it -v $(pwd)/tpl:/tpl --network docker-consul-vault-demo_consul-demo  hashicorp/consul-template -consul-addr "consul-server-bootstrap:8500" -template "/tpl/in.tpl:/tpl/out.txt" -once
#docker run --rm -it --network docker-consul-vault-demo_consul-demo -e CONSUL_HTTP_ADDR=http://consul-server-bootstrap:8500 consul:latest kv get -recurse /
networks:
  consul-demo:
